#!/usr/bin/env python3
"""
Markdown Timeline Generator
Converts a YAML/Markdown event list into a beautiful HTML timeline.

Usage:
    python main.py                    # Generate sample timeline
    python main.py events.yaml        # Generate from YAML file
"""

import sys
import yaml
from pathlib import Path
from datetime import datetime

SAMPLE_EVENTS = [
    {"date": "2024-01-15", "title": "Project Kickoff", "description": "Initial concept and planning phase"},
    {"date": "2024-02-01", "title": "First Prototype", "description": "Basic functionality working"},
    {"date": "2024-03-10", "title": "Beta Release", "description": "Public beta with core features"},
    {"date": "2024-05-20", "title": "v1.0 Launch", "description": "Official stable release"},
    {"date": "2024-08-01", "title": "Major Update", "description": "Performance improvements and new UI"},
    {"date": "2024-12-01", "title": "v2.0 Planning", "description": "Architecture redesign begins"},
]

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Timeline - Generated by Lizer</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 40px 20px; }}
  .container {{ max-width: 800px; margin: 0 auto; }}
  h1 {{ text-align: center; color: #58a6ff; margin-bottom: 10px; font-size: 2em; }}
  .subtitle {{ text-align: center; color: #8b949e; margin-bottom: 40px; }}
  .timeline {{ position: relative; padding: 20px 0; }}
  .timeline::before {{ content: ''; position: absolute; left: 50%; width: 2px; background: #30363d; transform: translateX(-50%); top: 0; bottom: 0; }}
  .event {{ position: relative; margin-bottom: 40px; display: flex; align-items: center; }}
  .event:nth-child(odd) {{ flex-direction: row-reverse; }}
  .event-content {{ width: 45%; padding: 20px; background: #161b22; border: 1px solid #30363d; border-radius: 8px; transition: all 0.3s; }}
  .event-content:hover {{ border-color: #58a6ff; transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.3); }}
  .event-date {{ color: #58a6ff; font-size: 0.85em; font-weight: 600; margin-bottom: 5px; }}
  .event-title {{ color: #f0f6fc; font-size: 1.1em; font-weight: 600; margin-bottom: 8px; }}
  .event-desc {{ color: #8b949e; font-size: 0.9em; line-height: 1.5; }}
  .dot {{ width: 16px; height: 16px; background: #58a6ff; border-radius: 50%; position: absolute; left: 50%; transform: translateX(-50%); border: 3px solid #0d1117; z-index: 1; }}
  .footer {{ text-align: center; margin-top: 40px; color: #484f58; font-size: 0.85em; }}
  @media (max-width: 600px) {{ .timeline::before {{ left: 20px; }} .event, .event:nth-child(odd) {{ flex-direction: row; justify-content: flex-end; }} .event-content {{ width: 80%; }} .dot {{ left: 20px; }} }}
</style>
</head>
<body>
<div class="container">
  <h1>Project Timeline</h1>
  <p class="subtitle">Key milestones and events</p>
  <div class="timeline">
{events}
  </div>
  <p class="footer">Generated by Markdown Timeline Generator | github.com/LizerAIDev/markdown-timeline</p>
</div>
</body>
</html>"""

EVENT_TEMPLATE = """    <div class="event">
      <div class="dot"></div>
      <div class="event-content">
        <div class="event-date">{date}</div>
        <div class="event-title">{title}</div>
        <div class="event-desc">{description}</div>
      </div>
    </div>"""


def load_events(input_file=None):
    """Load events from YAML file or use sample data"""
    if input_file and Path(input_file).exists():
        with open(input_file) as f:
            data = yaml.safe_load(f)
            return data.get("events", [])
    return SAMPLE_EVENTS


def generate(events, output="timeline.html"):
    """Generate HTML timeline"""
    sorted_events = sorted(events, key=lambda e: e.get("date", ""))
    events_html = "\n".join(EVENT_TEMPLATE.format(**e) for e in sorted_events)
    html = HTML_TEMPLATE.format(events=events_html)
    
    with open(output, "w") as f:
        f.write(html)
    
    print(f"Timeline generated: {output}")
    print(f"  Events: {len(sorted_events)}")
    print(f"  Date range: {sorted_events[0]['date']} → {sorted_events[-1]['date']}")


def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else None
    events = load_events(input_file)
    
    if not events:
        print("No events found. Create a YAML file with an 'events' list.")
        print("Example:")
        print("  events:")
        print("    - date: 2024-01-01")
        print("      title: My Event")
        print("      description: Something happened")
        return
    
    generate(events)


if __name__ == "__main__":
    main()
